
CREATE DATABASE RestauranteBD;

USE RestauranteBD;

-- TABLA CLIENTES
CREATE TABLE CLIENTES (
    nit VARCHAR(15) PRIMARY KEY,
    nombre VARCHAR(30),
    apellido VARCHAR(30),
    telefono VARCHAR(15),
    correo VARCHAR(60) UNIQUE
);

-- TABLA MESAS
CREATE TABLE MESAS (
    id INT PRIMARY KEY IDENTITY(1,1),
    capacidad INT,
    estado BIT
);

-- TABLA EMPLEADOS
CREATE TABLE EMPLEADOS (
    nit VARCHAR(15) PRIMARY KEY,
    nombre VARCHAR(30),
    apellido VARCHAR(30),
    cargo VARCHAR(20),
    telefono VARCHAR(15),
    correo VARCHAR(60) UNIQUE,
    salario FLOAT
);

-- TABLA MENUS
CREATE TABLE MENUS (
    id_menu INT PRIMARY KEY IDENTITY(1,1),
    nombre VARCHAR(50),
    precio FLOAT,
    descripcion TEXT
);

-- TABLA PLATOS
CREATE TABLE PLATOS (
    id INT PRIMARY KEY IDENTITY (1,1),
    nombre VARCHAR(30),
    precio FLOAT
);

-- TABLA ORDENES
CREATE TABLE ORDENES (
    id INT PRIMARY KEY IDENTITY(1,1),
    fecha DATE,
    hora TIME,
    nit_empleado VARCHAR(15),
    nit_cliente VARCHAR(15),
    id_mesa INT
);

-- TABLA DETALLE_ORDEN
CREATE TABLE DETALLE_ORDEN (
    id_detalle INT PRIMARY KEY IDENTITY(1,1),
    id_orden INT,
    id_menu INT
);

-- TABLA DETALLE_ORDEN_ADICIONAL
CREATE TABLE DETALLE_ORDEN_ADICIONAL (
    id INT PRIMARY KEY IDENTITY(1,1),
    id_detalle_orden INT,
    id_plato INT
);

-- TABLA PLATOS_MENU
CREATE TABLE PLATOS_MENU (
    id_plato_menu INT PRIMARY KEY IDENTITY(1,1),
    id_menu INT,
    id_plato INT
);

-- =============================================
-- CREACIÓN DE CLAVES FORÁNEAS
-- =============================================

-- ORDENES
ALTER TABLE ORDENES
ADD CONSTRAINT FK_ORDEN_EMPLEADO FOREIGN KEY (nit_empleado)
REFERENCES EMPLEADOS(nit);

ALTER TABLE ORDENES
ADD CONSTRAINT FK_ORDEN_CLIENTE FOREIGN KEY (nit_cliente)
REFERENCES CLIENTES(nit);

ALTER TABLE ORDENES
ADD CONSTRAINT FK_ORDEN_MESA FOREIGN KEY (id_mesa)
REFERENCES MESAS(id);

-- DETALLE_ORDEN
ALTER TABLE DETALLE_ORDEN
ADD CONSTRAINT FK_DETALLE_ORDEN_ORDEN FOREIGN KEY (id_orden)
REFERENCES ORDENES(id);

ALTER TABLE DETALLE_ORDEN
ADD CONSTRAINT FK_DETALLE_ORDEN_MENU FOREIGN KEY (id_menu)
REFERENCES MENUS(id_menu);

-- DETALLE_ORDEN_ADICIONAL
ALTER TABLE DETALLE_ORDEN_ADICIONAL
ADD CONSTRAINT FK_DETALLE_ORDEN_ADICIONAL_DETALLE FOREIGN KEY (id_detalle_orden)
REFERENCES DETALLE_ORDEN(id_detalle);

ALTER TABLE DETALLE_ORDEN_ADICIONAL
ADD CONSTRAINT FK_DETALLE_ORDEN_ADICIONAL_PLATO FOREIGN KEY (id_plato)
REFERENCES PLATOS(id);

-- PLATOS_MENU
ALTER TABLE PLATOS_MENU
ADD CONSTRAINT FK_PLATOS_MENU_MENU FOREIGN KEY (id_menu)
REFERENCES MENUS(id_menu);

ALTER TABLE PLATOS_MENU
ADD CONSTRAINT FK_PLATOS_MENU_PLATO FOREIGN KEY (id_plato)
REFERENCES PLATOS(id);